name: CarBengkel
favicon: null
layout_spectrum: 0.22625
typography_spectrum: 0.48804
title: Breakdown.Appointment.Quotation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f37835'
    - '#515a63'
    - '#a4a4a4'
    - '#fcbf79'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.406588
purpose: []
