analytics: {}
color:
  brandColors:
    - '#000000'
    - '#815204'
    - '#000000'
    - '#F8A820'
    - '#000000'
  brandStrength: 0.741228
  lightness: 0.375
  rhythmicContrast: 0.25
  saturation: 0
cta: {}
layout_spectrum: 0
name: CarBengkel
opengraph: {}
purpose: []
typography_spectrum: 0.48804
