name: CarBengkel
favicon: null
layout_spectrum: 0.58961
typography_spectrum: 0.21814
title: Breakdown.Appointment.Quotation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#815204'
    - '#000000'
    - '#F8A820'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
