analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#f37835'
    - '#515a63'
    - '#a4a4a4'
    - '#fcbf79'
  brandStrength: 0.283991
  lightness: 0.125
  rhythmicContrast: 0.406588
  saturation: 0.455043
cta: {}
layout_spectrum: 0.572368
name: CarBengkel
opengraph: {}
purpose: []
typography_spectrum: 0.48804
