analytics: {}
color:
  brandColors:
    - '#000000'
    - '#815204'
    - '#000000'
    - '#F8A820'
    - '#000000'
  brandStrength: 0.741228
  lightness: 0.375
  rhythmicContrast: 0.129385
  saturation: 0.293859
cta: {}
layout_spectrum: 0.997807
name: CarBengkel
opengraph: {}
purpose: []
typography_spectrum: 0.180921
